# # Use root/example as user/password credentials

# services:
#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#     ports:
#       - 3306:3306
# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-db:/var/lib/mysql
    networks:
      - app-network

  db1:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql-db1:/var/lib/mysql
    networks:
      - app-network

  db2:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
      POSTGRES_USER: pguser
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-db:/var/lib/postgresql
    networks:
      - app-network

  db-3:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
      POSTGRES_USER: pguser
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres-db3:/var/lib/postgresql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  # MongoDB services
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./data/mongo:/data/db

  mongo1:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - ./data/mongo1:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    networks:
      - app-network
    depends_on:
      - mongo

  mongo-express1:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo1:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    networks:
      - app-network
    depends_on:
      - mongo1

networks:
  app-network:
    driver: bridge
